# Generated by Django 4.0.3 on 2023-11-08 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Voca_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('is_share', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voca_book_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.voca_book'),
        ),
        migrations.DeleteModel(
            name='Word_List',
        ),
    ]
