# Generated by Django 4.0.3 on 2023-11-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_author_voca_book_alter_word_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='title',
            new_name='voca_book',
        ),
        migrations.RemoveField(
            model_name='word',
            name='author',
        ),
    ]
