# Generated by Django 4.0.3 on 2023-11-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_remove_voca_book_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voca_book',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='mean',
            field=models.TextField(null=True),
        ),
    ]
