# Generated by Django 4.0.3 on 2023-11-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_voca_book_create_date_word_content_word_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voca_book',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
