# Generated by Django 4.0.3 on 2023-11-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_voca_book_from_lang_voca_book_to_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voca_book',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='voca_book',
            name='to_lang',
        ),
    ]
