# Generated by Django 4.0.3 on 2023-11-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_remove_voca_book_from_lang_remove_voca_book_to_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='voca_book',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
