# Generated by Django 4.0.3 on 2023-11-14 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0009_voca_book_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='voca_book',
            name='voter',
            field=models.ManyToManyField(related_name='voca_book_voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
