# Generated by Django 4.0.3 on 2023-11-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0010_voca_book_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='voter',
            field=models.ManyToManyField(related_name='word_voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
