# Generated by Django 4.0.3 on 2023-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0012_alter_voca_book_is_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='voca_book',
            name='from_lang',
            field=models.CharField(default='en-US', max_length=50),
        ),
        migrations.AddField(
            model_name='voca_book',
            name='to_lang',
            field=models.CharField(default='ko-KR', max_length=50),
        ),
    ]
